language: node_js
node_js:
- "6"
- "8"
- "10"
cache:
  yarn: true
install:
  - yarn
script:
  - yarn build
  - yarn build:lkg
  - yarn cover
  - node lkg/bin/index
after_success:
  - yarn coveralls
  